# Generated by Django 5.0.2 on 2024-03-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0002_customuserprofile_ethereum_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
